[Mesh]
  [base]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 32
    ny = 32
    xmin = 0
    xmax = 1
    ymin = 0
    ymax = 1
    elem_type = QUAD9
  []
[]
[Variables]
  [ux]
    order = SECOND
    family = LAGRANGE
  []
  [uy]
    order = SECOND
    family = LAGRANGE
  []
  [p]
    order = FIRST
    family = LAGRANGE
  []
[]
# Generated by validation/mms_reference.py; original Apache-2.0 code.
[Functions]
  [exact_ux]
    type = ParsedFunction
    expression = '0.01*sin(t)*sin(3.1415926535897932*x)*sin(3.1415926535897932*y)'
  []
  [exact_uy]
    type = ParsedFunction
    expression = '0.01*sin(t)*sin(3.1415926535897932*y)*cos(3.1415926535897932*x)'
  []
  [exact_p]
    type = ParsedFunction
    expression = '0.01*sin(t)*cos(3.1415926535897932*x)*cos(3.1415926535897932*y)'
  []
  [body_x]
    type = ParsedFunction
    expression = '3.1515565942422978*sin(t)*sin(3.1415926535897932*x)*sin(3.1415926535897932*y) + 1.3245460864865644*sin(t)*sin(3.1415926535897932*x)*cos(3.1415926535897932*y) - 0.12432984966738327*sin(t)*sin(3.1415926535897932*y)*cos(3.1415926535897932*x) - 0.25368944761128726*sin(t)*cos(3.1415926535897932*x)*cos(3.1415926535897932*y)'
  []
  [body_y]
    type = ParsedFunction
    expression = '-0.12512338688923574*sin(t)*sin(3.1415926535897932*x)*sin(3.1415926535897932*y) - 0.50314268416790627*sin(t)*sin(3.1415926535897932*x)*cos(3.1415926535897932*y) + 3.2726710410860596*sin(t)*sin(3.1415926535897932*y)*cos(3.1415926535897932*x) - 1.3469953839903414*sin(t)*cos(3.1415926535897932*x)*cos(3.1415926535897932*y)'
  []
  [mass_source]
    type = ParsedFunction
    expression = '0.29608813203268076*sin(t)*cos(3.1415926535897932*x)*cos(3.1415926535897932*y) + 0.00079353722185247031*sin(3.1415926535897932*x)*sin(3.1415926535897932*y)*cos(t) - 0.00079353722185247031*sin(3.1415926535897932*x)*cos(t)*cos(3.1415926535897932*y) + 0.022449297503777064*sin(3.1415926535897932*y)*cos(t)*cos(3.1415926535897932*x) + 0.023990595361074087*cos(t)*cos(3.1415926535897932*x)*cos(3.1415926535897932*y)'
  []
[]
[ICs]
  [ux]
    type = ConstantIC
    variable = ux
    value = 0
  []
  [uy]
    type = ConstantIC
    variable = uy
    value = 0
  []
  [p]
    type = ConstantIC
    variable = p
    value = 0
  []
[]
[AuxVariables]
  [J]
    family = MONOMIAL
    order = CONSTANT
  []
  [Jbar]
    family = MONOMIAL
    order = CONSTANT
  []
  [solid_fraction]
    family = MONOMIAL
    order = CONSTANT
  []
  [stability]
    family = MONOMIAL
    order = CONSTANT
  []
  [energy]
    family = MONOMIAL
    order = CONSTANT
  []
  [B12]
    family = MONOMIAL
    order = CONSTANT
  []
  [sigma11]
    family = MONOMIAL
    order = CONSTANT
  []
  [sigma22]
    family = MONOMIAL
    order = CONSTANT
  []
  [sigma12]
    family = MONOMIAL
    order = CONSTANT
  []
  [mass_reaction]
    family = LAGRANGE
    order = FIRST
  []
  [force_reaction]
    family = LAGRANGE
    order = SECOND
  []
[]
[AuxKernels]
  [J]
    type = MaterialRealAux
    variable = J
    property = J
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [Jbar]
    type = MaterialRealAux
    variable = Jbar
    property = Jbar
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [solid_fraction]
    type = MaterialRealAux
    variable = solid_fraction
    property = solid_fraction
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [stability]
    type = MaterialRealAux
    variable = stability
    property = stability
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [energy]
    type = MaterialRealAux
    variable = energy
    property = energy
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [B12]
    type = MaterialRealAux
    variable = B12
    property = B12
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [sigma11]
    type = MaterialRealAux
    variable = sigma11
    property = sigma11
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [sigma22]
    type = MaterialRealAux
    variable = sigma22
    property = sigma22
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [sigma12]
    type = MaterialRealAux
    variable = sigma12
    property = sigma12
    execute_on = 'INITIAL TIMESTEP_END'
  []
[]
[Materials]
  [law]
    type = ConformalMaterial
    ux = ux
    uy = uy
    pressure = p
    mineral_stiffness = '50 12 10 0 0 0 12 60 14 0 0 0 10 14 70 0 0 0 0 0 0 20 0 0 0 0 0 0 24 0 0 0 0 0 0 28'
    solid_fraction = 0.6
    drained_bulk = 7
    fluid_bulk = 8
    mobility = 1.5
    angle = 30
    linear_reference = true
    log_quadrature = 12
  []
[]
[Kernels]
  [mx]
    type = ReferenceMomentum
    variable = ux
    component = 0
  []
  [my]
    type = ReferenceMomentum
    variable = uy
    component = 1
  []
  [mass]
    type = ReferenceFluidMass
    variable = p
  []
  [source_ux]
    type = BodyForce
    variable = ux
    function = body_x
  []
  [source_uy]
    type = BodyForce
    variable = uy
    function = body_y
  []
  [source_p]
    type = BodyForce
    variable = p
    function = mass_source
  []
[]
[BCs]
  [ux]
    type = FunctionDirichletBC
    variable = ux
    boundary = 'left right top bottom'
    function = exact_ux
  []
  [uy]
    type = FunctionDirichletBC
    variable = uy
    boundary = 'left right top bottom'
    function = exact_uy
  []
  [p]
    type = FunctionDirichletBC
    variable = p
    boundary = 'left right top bottom'
    function = exact_p
  []
[]
[Postprocessors]
  [ux_l2]
    type = ElementL2Error
    variable = ux
    function = exact_ux
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [uy_l2]
    type = ElementL2Error
    variable = uy
    function = exact_uy
    execute_on = 'INITIAL TIMESTEP_END'
  []
  [p_l2]
    type = ElementL2Error
    variable = p
    function = exact_p
    execute_on = 'INITIAL TIMESTEP_END'
  []
[]
[Preconditioning]
  [full]
    type = SMP
    full = true
  []
[]
[Executioner]
  type = Transient
  solve_type = NEWTON
  line_search = basic
  dt = 0.005
  end_time = 0.2
  scheme = implicit-euler
  nl_rel_tol = 1e-9
  nl_abs_tol = 1e-12
  nl_max_its = 15
  l_tol = 1e-9
  l_max_its = 200
  petsc_options_iname = '-pc_type -pc_factor_mat_solver_type'
  petsc_options_value = 'lu mumps'
[]
[Outputs]
  csv = true
  exodus = true
  execute_on = 'INITIAL TIMESTEP_END'
[]
