#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Re-run the pore-fabric decks and refresh the recorded evidence.

Round-22 revision harness. It runs every pore-fabric deck (and the paired
reviewed ``ConformalMaterial`` reference deck) with the compiled
``moose_app/anisotropic_biot-opt``, then copies the deck, scalar history,
recorded profiles, solver log, and a provenance record into
``fe-evidence/runs/<case>/``. The per-run ``analysis.json`` is regenerated by
``--analysis-only`` from ``build/fabric/fabric-verification.json`` (written by
``examples/verify_fabric.py``), so the documented order is:

    python3 tools/rerun_fabric_decks.py             # run every case
    python3 examples/verify_fabric.py               # independent NumPy check
    python3 tools/rerun_fabric_decks.py --analysis-only

Only recorded artifacts are written; the module certifies nothing by itself.
"""
import argparse
import csv
import datetime as dt
import hashlib
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BIN = ROOT / 'moose_app/anisotropic_biot-opt'
LIB = ROOT / 'moose_app/lib/libanisotropic_biot-opt.so.0.0.0'
DEST = ROOT / 'fe-evidence/runs'
SOURCE = 'moose_app/include/utils/FabricLaw.h, moose_app/src/materials/FabricMaterial.C'
FIELDS = ['B_par', 'B_per', 'ln_a', 'ln_h', 'J', 'Jbar', 'solid_fraction',
          'sigma11', 'sigma22']

# case -> (deck, command-line overrides)
CASES = [
    ('fabric_probe_iso', 'fabric_probe.i', ['Materials/law/fabric_coupling=0']),
    ('fabric_probe_coup_a0', 'fabric_probe.i', ['Materials/law/fabric_angle=0', 'Materials/law/fabric_coupling=0.4']),
    ('fabric_probe_coup_a45', 'fabric_probe.i', ['Materials/law/fabric_angle=45', 'Materials/law/fabric_coupling=0.4']),
    ('fabric_probe_coup_a90', 'fabric_probe.i', ['Materials/law/fabric_angle=90', 'Materials/law/fabric_coupling=0.4']),
    ('fabric_probe_conformal', 'fabric_probe.i', ['Materials/law/conformal_limit=true', 'Materials/law/fabric_volume_modulus=5.4']),
    ('fabric_probe_stiffaxial', 'fabric_probe.i', ['Materials/law/fabric_axial_modulus=1e6']),
    ('fabric_probe_softaxial', 'fabric_probe.i', ['Materials/law/fabric_axial_modulus=0.1']),
    ('fabric_probe_a0', 'fabric_probe.i', ['Materials/law/fabric_angle=0']),
    ('fabric_probe_a45', 'fabric_probe.i', ['Materials/law/fabric_angle=45']),
    ('fabric_probe_a90', 'fabric_probe.i', ['Materials/law/fabric_angle=90']),
    ('conformal_probe_ref', 'conformal_probe.i', []),
    ('fabric_mandel_iso', 'fabric_mandel.i', ['Materials/law/fabric_coupling=0']),
    ('fabric_mandel_coup_a0', 'fabric_mandel.i', ['Materials/law/fabric_angle=0']),
    ('fabric_mandel_coup_a45', 'fabric_mandel.i', ['Materials/law/fabric_angle=45']),
    ('fabric_mandel_coup_a90', 'fabric_mandel.i', ['Materials/law/fabric_angle=90']),
]
PROBE = [case for case, _, _ in CASES if case.startswith('fabric_probe_')]
MANDEL = [case for case, _, _ in CASES if case.startswith('fabric_mandel_')]


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def revision():
    return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=ROOT,
                          capture_output=True, text=True).stdout.strip()


def run_case(case, deck, overrides):
    """Run one deck in a temporary directory and record only its shipped files."""
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp)
        command = ['./moose_app/anisotropic_biot-opt', '-i', f'moose_app/inputs/{deck}',
                   f'Outputs/file_base={out}/solution', '--n-threads=1'] + overrides
        start = dt.datetime.now(dt.timezone.utc)
        proc = subprocess.run(command, cwd=ROOT, capture_output=True, text=True)
        end = dt.datetime.now(dt.timezone.utc)
        status = 'success' if proc.returncode == 0 else 'failed'
        if (DEST / case).exists():
            shutil.rmtree(DEST / case)
        (DEST / case).mkdir(parents=True, exist_ok=True)
        (DEST / case / 'run.log').write_text(proc.stdout + proc.stderr)
        provenance = dict(
            application='anisotropic_biot-opt (FabricMaterial)',
            application_sha256=sha(BIN),
            application_library_sha256=sha(LIB),
            git_revision=revision(),
            input_deck=deck,
            command_overrides=overrides,
            command=['./moose_app/anisotropic_biot-opt', '-i', f'moose_app/inputs/{deck}',
                     'Outputs/file_base=...'] + overrides,
            recorded_utc=end.isoformat(),
            exit_status=status,
            source=SOURCE,
        )
        (DEST / case / 'provenance.json').write_text(json.dumps(provenance, indent=2) + '\n')
        if proc.returncode != 0:
            print((proc.stdout + proc.stderr)[-2000:])
            return status
        if not (out / 'solution.csv').is_file():
            (DEST / case / 'provenance.json').write_text(
                json.dumps(dict(provenance, exit_status='failed-no-history'), indent=2) + '\n')
            return 'failed-no-history'
        shutil.copy2(out / 'solution.csv', DEST / case / 'solution.csv')
        for profile in sorted(out.glob('solution_profile_*.csv')):
            shutil.copy2(profile, DEST / case / profile.name)
        shutil.copy2(ROOT / 'moose_app/inputs' / deck, DEST / case / 'input.i')
    return status


def final_row(case):
    with open(DEST / case / 'solution.csv') as stream:
        row = list(csv.DictReader(stream))[-1]
    return {key: float(value) for key, value in row.items()}


def regenerate_analysis():
    report_path = ROOT / 'build/fabric/fabric-verification.json'
    if not report_path.is_file():
        raise SystemExit('run examples/verify_fabric.py before --analysis-only')
    report = json.loads(report_path.read_text())
    for case in PROBE:
        row = final_row(case)
        diff = report['cases'][case]['abs_diff']
        out = dict(row)
        out['verification'] = {
            'fields_checked': FIELDS,
            'independent_max_abs_diff': max(diff.values()),
            'reference': 'examples/verify_fabric.py (NumPy re-implementation of sections/pore_fabric.tex)',
        }
        (DEST / case / 'analysis.json').write_text(json.dumps(out, indent=2, sort_keys=True) + '\n')
    for case in MANDEL:
        (DEST / case / 'analysis.json').write_text(
            json.dumps(final_row(case), indent=2, sort_keys=True) + '\n')
    row = final_row('conformal_probe_ref')
    out = {key: row[key] for key in ('J', 'Jbar', 'sigma11', 'sigma22', 'solid_fraction', 'time')}
    out['verification'] = {
        'max_abs_diff_vs_independent': max(v['abs_diff']
                                           for v in report['conformal_cross_check'].values()),
        'role': 'reference run of the reviewed ConformalMaterial at the same prescribed state',
    }
    (DEST / 'conformal_probe_ref' / 'analysis.json').write_text(
        json.dumps(out, indent=2, sort_keys=True) + '\n')
    print('regenerated analysis.json for', len(PROBE), 'probe +', len(MANDEL), 'mandel + reference')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--analysis-only', action='store_true',
                        help='regenerate analysis.json from the recorded histories and report')
    args = parser.parse_args()
    if args.analysis_only:
        regenerate_analysis()
        return
    print('git', revision(), 'app', sha(BIN), 'library', sha(LIB))
    results = {}
    for case, deck, overrides in CASES:
        results[case] = run_case(case, deck, overrides)
        print(f'{case:26s} {results[case]}', flush=True)
    print(json.dumps(results, indent=2))
    if any(status != 'success' for status in results.values()):
        raise SystemExit('one or more fabric decks failed')


if __name__ == '__main__':
    main()
